name: Deploy React App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Deploy React to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: reacttestground-bmb0e0gkb7cabwf2
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./build
